name: Python CI for Calculator App

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest  # Install linter and testing tools

    # Step 4: Run flake8 (Linting the code)
    - name: Lint code with flake8
      run: |
        echo "Running flake8 for code linting"
        flake8 calculator.py test_calculator.py  # Lint both the main app and the test files

    # Step 5: Run tests with pytest
    - name: Run unit tests
      run: |
        echo "Running tests with pytest"
        pytest test_calculator.py  # Run the unit tests on the test_calculator.py file

