name: Python Application

on:
  push:
    branches:
      - main   # Trigger the workflow on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Step 3: Install dependencies (flake8 for linting)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    # Step 4: Run flake8 for linting the Python code
    - name: Lint code with flake8
      run: |
        echo "Running flake8 for code linting"
        flake8 calculator.py test_calculator.py  # Lint both files

    # Step 5: Run the Python calculator script (calculator.py)
    - name: Run Python script
      run: |
        echo "Running Python calculator script"
        python calculator.py  # Run the calculator app
